### ISSUE TITLE
How do I get the full dataset? 

### ISSUE THREAD

**Issue by dcahn12** [StanLei52/AQVSR#1]
How do I get the full dataset? 
In the linked g-drive, there are only image and annotation-related files.
Where are the videos (or video features you use)?
Do I need separately to download Howto100M videos that are selected for your 210 videos?

**Comment by StanLei52** [comment]
Hi, thank you for asking. 
1. All the videos can be downloaded from youtube: in the `json` and `csv` folder, we name each file by the youtube video id -- you can download the raw videos from youtube according to these ids (e.g., using `youtube-dl`). Note that the videos are **not** from the HowTo100M.
2. For preprocessing and feature extraction, please check this repo if you want to follow our paper: https://github.com/Yuxuan-W/AIAssistPreprocess.
