### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by V1ncentDemo** [StanLei52/AQVSR#2]
Hello, is the dataset of this paper completely provided? I encountered data processing problems when reproducing the code of this paper. Are the data sets such as trainset.jsonl, validset.jsonl, testset.jsonl and feature.hdf5 not provided in the data set? I would be grateful if the corresponding data can be provided.

**Comment by StanLei52** [comment]
Hi, please see [release](https://github.com/StanLei52/TQVSR/releases/tag/v1.0.0) for the processed data.
